baseURL: "https://www.sidlibrary.org/"
defaultContentLanguage: en

enableRobotsTXT: true
paginate: 10
summaryLength: 60

outputs:
  home:
    - html
    - rss
    - json

theme: "PaperMod"
_merge: shallow

title: "The Discouraged Revolutionary's Hidden Den"

params:
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  author: Sidney Jeong
  dateFormat: "2006-01-02"
      
  titleCaseStyle: chicago

  defaultTheme: dark
  disableThemeToggle: false
 
  profileMode:
    enabled: true

  socialIcons:
    - name: email
      url: "mailto:jeong.sid@sidlibrary.org"
    - name: linkedin
      url: "https://www.linkedin.com/in/sidney-jeong-56b52449/"
    - name: github
      url: "https://github.com/sid0831"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 
    keys: ["title", "permalink", "summary", "content"]

  pygmentsUseClasses: true

  assets:
    disableHLJS: true
  
  footer:
    text: |
      All contents from myself on this site are freely available under [Creative Commons License by-sa 4.0](https://creativecommons.org/licenses/by-sa/4.0/) unless otherwise specified.  
      The opinions and views the contents might present are solely my personal ones, and unrelated to any organisation or group I belong to.  
    disclaimer: |
      이 블로그의 모든 내용과 견해는 저의 개인적인 것이며, 제가 속해 있는 어떤 회사, 기관, 또는 집단과도 무관합니다.  
      이 블로그에 저의 개인정보가 공개된 경우 이는 제가 그 정보의 처리(수집·이용)에 동의함을 의미하지 않습니다.

languages:
  en:
    languageCode: en
    languageName: English
    languageDirection: ltr
    weight: 1

    params:
      description: "The den for evidence-based revolution"
      profileMode:
        title: |
          We must think! But what we must?
        subtitle: |
          Hello there! I'm Sidney Jeong, a neurodivergent queer tech worker who decided to leave the world of academia in social science many years ago for this new journey of career and life.

          <span style="font-size: 12px; font-style: italic;">Please note that the blog is going under an overhaul. I'll try to fill the contents back soon.</span>
        imageUrl: "logo.png"
        imageTitle: The logo of this blog. It is an imaginary coat of arms of the Republic of Dreamcatcher.
    
    menu:
      main:
        - identifier: home
          name: Home
          pageRef: /
          weight: 1
        - identifier: blog
          name: Blog
          pageRef: /blog/
          weight: 10
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 30
        - identifier: about-me
          name: About Me
          url: /about-me/
          weight: 40

  ko:
    disabled: true

    languageCode: ko
    languageName: 한국어(Korean)
    languageDirection: ltr
    weight: 2

    params:
      description: "The den for evidence-based revolution"

      profileMode:
        title: |
          우리는 생각해야 한다. 그러나 무엇을?
        subtitle: |
          Hello there! I'm Sidney Jeong, a neurodivergent queer tech worker who decided to leave the world of academia in social science many years ago for this new journey of career and life.

          <span style="font-size: 12px; font-style: italic;">Please note that the blog is going under an overhaul. I'll try to fill the contents back soon.</span>
        imageUrl: "logo.png"
        imageTitle: The logo of this blog. It is an imaginary coat of arms of the Republic of Dreamcatcher.

    menu:
      main:
        - identifier: home
          name: "홈"
          pageRef: /
          weight: 1
        - identifier: blog
          name: "블로그"
          pageRef: /blog/
          weight: 10
        - identifier: archives
          name: "아카이브"
          url: /archives/
          weight: 20
        - identifier: search
          name: "검색"
          url: /search/
          weight: 30
        - identifier: about-me
          name: "소개"
          url: /about-me/
          weight: 40
